datasets:
  maternal-health-risk:
    column_mapping:
      numerical_features:
        - 'Age'
        - 'SystolicBP'
        - 'DiastolicBP'
        - 'BS'
        - 'BodyTemp'
        - 'HeartRate'
      target: 'RiskLevel'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - cat_target_drift
    reference_file: ./datasets/data.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 50
